os:
  editCommand: "floaterm"
  edit: "nv {{filename}}"
  editAtLine: "nv +{{line}} {{filename}}"
  editInTerminal: true

keybinding:
  universal:
    return: "<esc>"
    return-alt1: "q"
    quit: "<c-c>"

gui:
  sidePanelWidth: 0.2
  language: auto
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline

git:
  paging:
    colorArg: never
    pager: delta --dark --paging=never
