os:
  editCommand: "floaterm"

keybinding:
  universal:
    return: "<esc>"
    return-alt1: "q"
    quit: "<c-c>"

gui:
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline

git:
  paging:
    colorArg: never
    pager: delta --dark --paging=never
