# remap C-b to C-a
# https://koenwoortman.com/tmux-remap-ctrl-b-to-ctrl-a/
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# support true color
set -g default-terminal "screen-256color"
# start window numbering at 1
set -g base-index 1

# scroll with mouse
set -g mouse on
# splitting panes with | and -
bind | split-window -h
bind - split-window -v
# moving between panes with Prefix h,j,k,l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# Quick window selection
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5
