os:
  edit: "nv {{filename}}"
  editAtLine: "nv +{{line}} {{filename}}"
  editInTerminal: true

keybinding:
  universal:
    return: "<esc>"
    return-alt1: "q"
    quit: "<c-c>"

gui:
  sidePanelWidth: 0.2
  language: auto
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline

git:
  paging:
    colorArg: never
    pager: delta --dark --paging=never

customCommands:
  - key: '<c-f>'
    command: "nv -n -c \"DiffviewOpen {{.SelectedLocalCommit.Sha}}~1..{{.SelectedLocalCommit.Sha}}\""
    context: 'commits'
    subprocess: true
    description: 'Compare (difftool) with local copy'
      
  - key: 'F'
    command: "nv -n -c \"DiffviewOpen {{.SelectedLocalCommit.Sha}}\""
    context: 'commits'
    subprocess: true
    description: 'Compare (difftool) with worktree'
    
  - key: '<c-f>'
    command: "nv -n -c \"DiffviewOpen {{.SelectedLocalCommit.Sha}}~1..{{.SelectedLocalCommit.Sha}} -- {{.SelectedCommitFile.Name}}\""
    context: 'commitFiles'
    subprocess: true
    description: 'Compare (difftool) with local copy'
